name: artswellfyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  logger: ^2.5.0
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.12.1
  connectivity_plus: ^6.1.3
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  pinput: ^5.0.1
#  flutter_native_splash: ^2.4.4

  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  #  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/images/categories/
    - assets/images/promotionImages/
    - assets/images/storeImages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #flutter_native_splash:
  #  color: "#F7E7D4"
  #  image: assets/images/splashScreenLogo.png
  #  android: true
  ##  ios: true
  #  #  web: true
  #  fullscreen: true
  #
  #  android_12:
  #    color: "#F7E7D4"
  #    image: assets/images/splashScreenLogo.png
  #    android: true
  ##    ios: true
  #    fullscreen: true

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
