// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Kv41hrcFzieIVFl6gs7PR8NH9F45iwk',
    appId: '1:908319216413:web:b6c99cfa690ba51d7907f4',
    messagingSenderId: '908319216413',
    projectId: 'funoon-95f59',
    authDomain: 'funoon-95f59.firebaseapp.com',
    storageBucket: 'funoon-95f59.firebasestorage.app',
    measurementId: 'G-GXRXZJEPEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsDAPt1jUjaFAZge6iS_KY7AzaoHY70E',
    appId: '1:908319216413:android:20bddaa6433a8ca57907f4',
    messagingSenderId: '908319216413',
    projectId: 'funoon-95f59',
    storageBucket: 'funoon-95f59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5aXUVI-sasIqh9W87UQVDs8uFoc33qpo',
    appId: '1:908319216413:ios:41b2697af63f1e647907f4',
    messagingSenderId: '908319216413',
    projectId: 'funoon-95f59',
    storageBucket: 'funoon-95f59.firebasestorage.app',
    androidClientId: '908319216413-3cr8ntrud8ab9s77mp4v9ttn0oee1rhs.apps.googleusercontent.com',
    iosClientId: '908319216413-7el5p3gu7maogs12qlkc8gkfqe0bgisc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5aXUVI-sasIqh9W87UQVDs8uFoc33qpo',
    appId: '1:908319216413:ios:41b2697af63f1e647907f4',
    messagingSenderId: '908319216413',
    projectId: 'funoon-95f59',
    storageBucket: 'funoon-95f59.firebasestorage.app',
    iosBundleId: 'com.example.ecomfinal',
  );
}